# development:
#   adapter: postgresql
#   encoding: unicode
#   database: newdb
#   pool: 5
#   host: localhost
# development:
#   adapter: pg
#   database: newdb
#   host: localhost
#   encoding: unicode
#   port: 5432
#   pool: 50
#   prepared_statements: false
development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: altcoin_buzz_dev
  socket: /tmp/mysql.sock
  username: root
  # password: *password*

production:
  url: <%= ENV['CLEARDB_DATABASE_URL'] %>

# test:
#   adapter: sqlite3
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000
