development:
  adapter: postgresql
  database: altcoin_buzz_dev
  host: localhost
  encoding: unicode
  port: 5432
  pool: 50
  prepared_statements: false

test:
  adapter: postgresql
  database: altcoin_buzz_test
  host: localhost
  encoding: unicode
  port: 5432
  pool: 50
  prepared_statements: false

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  encoding: unicode
  prepared_statements: false
# development:
#   adapter: pg
#   database: newdb
#   host: localhost
#   encoding: unicode
#   port: 5432
#   pool: 50
#   prepared_statements: false
# development:
#   adapter: mysql2
#   encoding: utf8mb4
#   reconnect: false
#   database: altcoin_buzz_dev
#   socket: /tmp/mysql.sock
#   username: root
  # password: *password*

production:
  url: <%= ENV['CLEARDB_DATABASE_URL'] %>

# test:
#   adapter: sqlite3
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000
